<a href="https://colab.research.google.com/github/aminnademi/Clinical-Synthetic-Data-Audit/blob/main/pima.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
pip install sdv

Requirement already satisfied: sdv in /usr/local/lib/python3.13/dist-packages (1.38.3)
Requirement already satisfied: boto3<2.0.0,>=1.28 in /usr/local/lib/python3.13/dist-packages (from sdv) (1.43.89)
Requirement already satisfied: botocore<2.0.0,>=1.31 in /usr/local/lib/python3.13/dist-packages (from sdv) (1.43.89)
Requirement already satisfied: cloudpickle>=2.1.0 in /usr/local/lib/python3.13/dist-packages (from sdv) (3.1.2)
Requirement already satisfied: graphviz>=0.13.2 in /usr/local/lib/python3.13/dist-packages (from sdv) (0.21)
Requirement already satisfied: numpy>=2.1.0 in /usr/local/lib/python3.13/dist-packages (from sdv) (2.1.3)
Requirement already satisfied: pandas<3,>=2.2.3 in /usr/local/lib/python3.13/dist-packages (from sdv) (2.2.3)
Requirement already satisfied: tqdm>=4.29 in /usr/local/lib/python3.13/dist-packages (from sdv) (4.67.3)
Requirement already satisfied: copulas>=0.12.1 in /usr/local/lib/python3.13/dist-packages (from sdv) (0.14.1)
Requirement already satisfied: ctgan>=0.11.1 in /usr/local/lib/python3.13/dist-packages (from sdv) (0.12.1)
Requirement already satisfied: deepecho>=0.7.0 in /usr/local/lib/python3.13/dist-packages (from sdv) (0.8.1)
Requirement already satisfied: rdt>=1.18.2 in /usr/local/lib/python3.13/dist-packages (from sdv) (1.22.0)
Requirement already satisfied: sdmetrics>=0.30.0 in /usr/local/lib/python3.13/dist-packages (from sdv) (0.31.0)
Requirement already satisfied: platformdirs>=4.0 in /usr/local/lib/python3.13/dist-packages (from sdv) (4.11.4)
Requirement already satisfied: pyyaml>=6.0.1 in /usr/local/lib/python3.13/dist-packages (from sdv) (6.0.3)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.13/dist-packages (from boto3<2.0.0,>=1.28->sdv) (1.1.0)
Requirement already satisfied: s3transfer<0.20.0,>=0.19.0 in /usr/local/lib/python3.13/dist-packages (from boto3<2.0.0,>=1.28->sdv) (0.19.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.13/dist-packages (from botocore<2.0.0,>=1.31->sdv) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.13/dist-packages (from botocore<2.0.0,>=1.31->sdv) (2.5.0)
Requirement already satisfied: plotly>=5.12.0 in /usr/local/lib/python3.13/dist-packages (from copulas>=0.12.1->sdv) (5.24.1)
Requirement already satisfied: scipy>=1.14.1 in /usr/local/lib/python3.13/dist-packages (from copulas>=0.12.1->sdv) (1.16.3)
Requirement already satisfied: torch>=2.6.0 in /usr/local/lib/python3.13/dist-packages (from ctgan>=0.11.1->sdv) (2.11.0+cu128)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<3,>=2.2.3->sdv) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<3,>=2.2.3->sdv) (2026.3)
Requirement already satisfied: scikit-learn>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from rdt>=1.18.2->sdv) (1.6.1)
Requirement already satisfied: Faker!=37.11.0,>=17 in /usr/local/lib/python3.13/dist-packages (from rdt>=1.18.2->sdv) (40.38.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly>=5.12.0->copulas>=0.12.1->sdv) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from plotly>=5.12.0->copulas>=0.12.1->sdv) (26.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.31->sdv) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.5.2->rdt>=1.18.2->sdv) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.5.2->rdt>=1.18.2->sdv) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (3.32.4)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.6.0->ctgan>=0.11.1->sdv) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.13/dist-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.13/dist-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.6.0->ctgan>=0.11.1->sdv) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.6.0->ctgan>=0.11.1->sdv) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.6.0->ctgan>=0.11.1->sdv) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.6.0->ctgan>=0.11.1->sdv) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.6.0->ctgan>=0.11.1->sdv) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.6.0->ctgan>=0.11.1->sdv) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.6.0->ctgan>=0.11.1->sdv) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.6.0->ctgan>=0.11.1->sdv) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.6.0->ctgan>=0.11.1->sdv) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.6.0->ctgan>=0.11.1->sdv) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.6.0->ctgan>=0.11.1->sdv) (12.8.90)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=2.6.0->ctgan>=0.11.1->sdv) (1.7.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=2.6.0->ctgan>=0.11.1->sdv) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=2.6.0->ctgan>=0.11.1->sdv) (3.0.3)

# Import Required Libraries

In [51]:
import os
import random
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

from scipy.stats import wasserstein_distance

from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression

import sdv
from sdv.metadata import SingleTableMetadata
from sdv.single_table import CTGANSynthesizer, TVAESynthesizer

In [52]:
SEED = 42
TEST_SIZE = 0.30
N_SYNTHETIC = 1000

OUT_DIR = Path("pima_benchmark_outputs")
OUT_DIR.mkdir(parents=True, exist_ok=True)

TARGET = "Outcome"

def set_seed(seed=SEED):
    random.seed(seed)
    np.random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)

set_seed()

# Load Dataset & EDA

In [53]:
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ["Pregnancies", "Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI", "DiabetesPedigreeFunction", "Age", "Outcome"]

df = pd.read_csv(url, header=None, names=columns)

In [54]:
df.shape

(768, 9)

In [55]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [56]:
display(df.describe())

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [57]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

### Data Separation

In [58]:
train_df, test_df = train_test_split(
    df,
    test_size=TEST_SIZE,
    random_state=SEED,
    stratify=df[TARGET],
)

train_df = train_df.reset_index(drop=True)
test_df = test_df.reset_index(drop=True)

### Handling Logical Missing Values

In [59]:
def prepare_data(data):
    X = data[FEATURES].copy()
    y = data[TARGET].astype(int).copy()

    # Replace invalid zeros with NaN
    for col in Zeros:
        X[col] = X[col].replace(0, np.nan)

    return X, y

Zeros = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI",]

FEATURES = df.columns

# Prepare train and test
X_train, y_train = prepare_data(train_df)
X_test, y_test = prepare_data(test_df)


# KNN imputation: fit only on train
imputer = KNNImputer(n_neighbors=5)

X_train = pd.DataFrame(
    imputer.fit_transform(X_train),
    columns=FEATURES,
    index=X_train.index
)

X_test = pd.DataFrame(
    imputer.transform(X_test),
    columns=FEATURES,
    index=X_test.index
)


# Training data for the generators
train_model_df = X_train.copy()
train_model_df[TARGET] = y_train

### SDV for Metadata

In [60]:
metadata = SingleTableMetadata()

metadata.detect_from_dataframe(train_model_df)

metadata.update_column(
    column_name=TARGET,
    sdtype="categorical"
)

display(pd.DataFrame(
    metadata.to_dict()["columns"]
).T)

                               sdtype
Pregnancies                 numerical
Glucose                     numerical
BloodPressure               numerical
SkinThickness               numerical
Insulin                     numerical
BMI                         numerical
DiabetesPedigreeFunction    numerical
Age                         numerical
Outcome                   categorical

### Train CTGAN & TVAE

In [63]:
CTGAN_EPOCHS = 300
TVAE_EPOCHS = 300

ctgan = CTGANSynthesizer(
    metadata=metadata,
    epochs=CTGAN_EPOCHS,
    enforce_min_max_values=False,
    enforce_rounding=True,
    verbose=False,
)

tvae = TVAESynthesizer(
    metadata=metadata,
    epochs=TVAE_EPOCHS,
    enforce_min_max_values=False,
    enforce_rounding=True,
    verbose=False,
)

print("[+] Training CTGAN...")
set_seed(SEED)
ctgan.fit(train_model_df)

print("[+] Training TVAE...")
set_seed(SEED)
tvae.fit(train_model_df)

print("[+] Finished.")

/usr/local/lib/python3.13/dist-packages/sdv/single_table/base.py:183: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)

[+] Training CTGAN...
[+] Training TVAE...
[+] Finished.

### Generate 1000 Records

In [64]:
synthetic = {}

print("[+] Sampling CTGAN...")
set_seed(SEED)

synthetic["CTGAN"] = ctgan.sample(
    num_rows=N_SYNTHETIC
)

print("[+] Sampling TVAE...")
set_seed(SEED)

synthetic["TVAE"] = tvae.sample(
    num_rows=N_SYNTHETIC
)

for name in synthetic:
    data = synthetic[name].copy()

    # target را binary نگه می‌داریم
    data[TARGET] = (
        pd.to_numeric(
            data[TARGET],
            errors="coerce"
        )
        .round()
        .clip(0, 1)
        .astype(int)
    )

    synthetic[name] = data

    data.to_csv(
        OUT_DIR / f"{name.lower()}_raw.csv",
        index=False
    )

print({
    name: data.shape
    for name, data in synthetic.items()
})

[+] Sampling CTGAN...
[+] Sampling TVAE...
{'CTGAN': (1000, 9), 'TVAE': (1000, 9)}