# Initialize TabDDPM Repo & Setup Dependencies

In [1]:
# Clone the official repository
import os
%cd /content
if not os.path.exists('/content/tab-ddpm'):
    !git clone https://github.com/yandex-research/tab-ddpm.git
%cd /content/tab-ddpm

/content
Cloning into 'tab-ddpm'...
remote: Enumerating objects: 699, done.
remote: Counting objects: 100% (326/326), done.
remote: Compressing objects: 100% (142/142), done.
remote: Total 699 (delta 205), reused 184 (delta 184), pack-reused 373 (from 1)
Receiving objects: 100% (699/699), 221.52 KiB | 1.57 MiB/s, done.
Resolving deltas: 100% (333/333), done.
/content/tab-ddpm

In [2]:
# Create an isolated Python 3.9.7 environment
MINIFORGE = '/content/miniforge3'
ENV = '/content/miniforge3/envs/tddpm'

if not os.path.exists(MINIFORGE):
    !wget -q https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -O /content/miniforge.sh
    !bash /content/miniforge.sh -b -p /content/miniforge3

if not os.path.exists(ENV):
    !/content/miniforge3/bin/conda create -y -n tddpm python=3.9.7

!/content/miniforge3/bin/conda run -n tddpm python --version

PREFIX=/content/miniforge3
Unpacking bootstrapper...
Unpacking payload...
Extracting ca-certificates-2026.7.22-hbd8a1cb_0.conda
Extracting libgomp-16.1.0-he0feb66_1.conda
Extracting libzlib-1.3.2-h25fd6f3_3.conda
Extracting nlohmann_json-abi-3.12.0-h0f90c79_2.conda
Extracting pybind11-abi-11-hc364b38_1.conda
Extracting python_abi-3.14-8_cp314.conda
Extracting tzdata-2026c-h151e31d_0.conda
Extracting _openmp_mutex-4.5-20_gnu.conda
Extracting zstd-1.5.7-hb78ec9c_7.conda
Extracting ld_impl_linux-64-2.46.1-default_hbd61a6d_102.conda
Extracting libgcc-16.1.0-ha9f2e26_1.conda
Extracting bzip2-1.0.8-hda65f42_10.conda
Extracting c-ares-1.34.8-h280c20c_1.conda
Extracting keyutils-1.6.3-h7cc23a3_1.conda
Extracting libev-4.33-h280c20c_3.conda
Extracting libexpat-2.8.1-hecca717_1.conda
Extracting libffi-3.7.0-h3435931_0.conda
Extracting libiconv-1.18-h3b78370_2.conda
Extracting liblzma-5.8.3-hb03c661_1.conda
Extracting libmpdec-4.0.0-hb03c661_2.conda
Extracting libstdcxx-16.1.0-h934c35e_1.conda
Extracting libuuid-2.42.2-h5347b49_0.conda
Extracting lzo-2.10-h280c20c_1002.conda
Extracting ncurses-6.6-hdb14827_1.conda
Extracting openssl-3.6.3-h35e630c_1.conda
Extracting reproc-14.2.7.post0-h54a6638_2.conda
Extracting tk-8.6.13-noxft_hd70dff1_3.conda
Extracting cpp-expected-1.3.1-h171cf75_1.conda
Extracting fmt-12.1.0-h76c4fd7_1.conda
Extracting icu-78.3-py310h44b86e0_2.conda
Extracting libedit-3.1.20250104-pl5321h373387f_1.conda
Extracting libnghttp2-1.68.1-h877daf1_0.conda
Extracting libsolv-0.7.39-h9463b59_0.conda
Extracting libssh2-1.11.1-h6154650_1.conda
Extracting lz4-c-1.10.0-hee9eb32_2.conda
Extracting readline-8.3-h853b02a_0.conda
Extracting reproc-cpp-14.2.7.post0-h50b1954_2.conda
Extracting simdjson-4.2.4-hb700be7_0.conda
Extracting yaml-cpp-0.8.0-h54a6638_1.conda
Extracting krb5-1.22.2-hbc21106_2.conda
Extracting libpsl-0.23.1-hf670292_0.conda
Extracting libsqlite-3.53.4-hf4e2dac_0.conda
Extracting libxml2-16-2.15.3-hca6bf5a_0.conda
Extracting spdlog-1.17.0-hb6aa676_2.conda
Extracting libcurl-8.21.0-heca4667_4.conda
Extracting libxml2-2.15.3-h49c6c72_0.conda
Extracting python-3.14.6-h242f9ac_102_cp314.conda
Extracting libarchive-3.8.9-gpl_hc2c16d8_100.conda
Extracting tomli-w-1.2.0-pyhd8ed1ab_0.conda
Extracting libmamba-2.5.0-hd28c85e_0.conda
Extracting menuinst-2.5.2-py314h9e666f3_1.conda
Extracting archspec-0.2.5-pyhd8ed1ab_0.conda
Extracting backports.zstd-1.6.0-py314h680f03e_0.conda
Extracting boltons-26.1.0-pyhd8ed1ab_0.conda
Extracting brotli-python-1.2.0-py314hcd2bdb6_3.conda
Extracting cached_property-1.5.2-pyha770c72_2.conda
Extracting certifi-2026.7.22-pyhd8ed1ab_0.conda
Extracting charset-normalizer-3.5.0-pyhd8ed1ab_0.conda
Extracting colorama-0.4.6-pyhd8ed1ab_1.conda
Extracting cpython-3.14.6-py314hd8ed1ab_102.conda
Extracting distro-1.9.0-pyhd8ed1ab_1.conda
Extracting filelock-3.32.3-pyhd8ed1ab_0.conda
Extracting frozendict-2.4.7-pyh851646a_2.conda
Extracting hpack-4.2.0-pyhd8ed1ab_0.conda
Extracting hyperframe-6.1.0-pyhd8ed1ab_0.conda
Extracting idna-3.18-pyhcf101f3_0.conda
Extracting jsonpointer-3.1.1-pyhcf101f3_0.conda
Extracting libmamba-spdlog-2.5.0-h12fcf84_0.conda
Extracting mamba-2.5.0-h9835478_0.conda
Extracting markupsafe-3.0.3-py314h67df5f8_1.conda
Extracting msgpack-python-1.2.1-py314h97ea11e_1.conda
Extracting packaging-26.3-pyhc364b38_0.conda
Extracting pip-26.2.1-pyh145f28c_0.conda
Extracting platformdirs-4.11.3-pyhcf101f3_0.conda
Extracting pluggy-1.6.0-pyhf9edf01_1.conda
Extracting pycosat-0.6.6-py314h5bd0f2a_4.conda
Extracting pycparser-3.0-pyhcf101f3_0.conda
Extracting pysocks-1.7.1-pyha55dd90_7.conda
Extracting python-installer-1.0.1-pyh332efcf_0.conda
Extracting ruamel.yaml.clib-0.2.15-py314h0f05182_1.conda
Extracting setuptools-84.0.0-pyh332efcf_0.conda
Extracting sniffio-1.3.1-pyhd8ed1ab_2.conda
Extracting tomli-2.4.1-pyhcf101f3_0.conda
Extracting tqdm-4.70.0-pyh8f84b5b_0.conda
Extracting truststore-0.10.4-pyhcf101f3_0.conda
Extracting typing_extensions-4.16.0-pyhcf101f3_0.conda
Extracting zipp-4.1.0-pyhcf101f3_0.conda
Extracting cached-property-1.5.2-hd8ed1ab_2.conda
Extracting cffi-2.1.1-py314h8d76f0c_2.conda
Extracting conda-package-streaming-0.13.0-pyhd8ed1ab_0.conda
Extracting exceptiongroup-1.3.1-pyhd8ed1ab_0.conda
Extracting h11-0.16.0-pyhcf101f3_1.conda
Extracting h2-4.4.1-pyhcf101f3_0.conda
Extracting importlib-metadata-9.0.0-pyhcf101f3_0.conda
Extracting jinja2-3.1.6-pyhcf101f3_1.conda
Extracting jsonpatch-1.33-pyhd8ed1ab_1.conda
Extracting libmambapy-2.5.0-py314hcbd71af_0.conda
Extracting pyproject_hooks-1.2.0-pyhd8ed1ab_1.conda
Extracting python-gil-3.14.6-h4df99d1_102.conda
Extracting ruamel.yaml-0.18.17-py314h0f05182_2.conda
Extracting typing-extensions-4.16.0-h69aa097_0.conda
Extracting typing-inspection-0.4.3-pyhcf101f3_0.conda
Extracting _python_abi3_support-1.0-hd8ed1ab_3.conda
Extracting annotated-types-0.8.0-pyhd8ed1ab_0.conda
Extracting anyio-4.14.2-pyhcf101f3_0.conda
Extracting conda-libmamba-solver-26.7.0-pyhcf101f3_0.conda
Extracting pydantic-core-2.46.4-py314h2e6c369_0.conda
Extracting python-build-1.5.0-pyhc364b38_0.conda
Extracting urllib3-2.7.0-pyhd8ed1ab_0.conda
Extracting zstandard-0.25.0-py314h0f05182_1.conda
Extracting httpcore-1.0.9-pyh29332c3_0.conda
Extracting py-rattler-0.25.0-py310h70157a2_2.conda
Extracting pydantic-2.13.4-pyhcf101f3_0.conda
Extracting requests-2.34.2-pyhcf101f3_0.conda
Extracting conda-package-handling-2.5.0-pyhcf101f3_0.conda
Extracting httpx-0.28.1-pyhd8ed1ab_0.conda
Extracting unearth-0.18.2-pyhd8ed1ab_0.conda
Extracting conda-pypi-0.11.0-py314h9e666f3_1.conda
Extracting conda-index-0.12.1-pyhd8ed1ab_0.conda
Extracting conda-lockfiles-0.2.1-pyhd8ed1ab_0.conda
Extracting conda-rattler-solver-0.1.1-pyhcf101f3_0.conda
Extracting conda-26.5.3-py314h9e666f3_2.conda
Extracting conda-self-0.2.1-pyhd8ed1ab_0.conda

Installing base environment...

Transaction

  Prefix: /content/miniforge3

  Updating specs:

   - ca-certificates==2026.7.22=hbd8a1cb_0
   - libgomp==16.1.0=he0feb66_1
   - libzlib==1.3.2=h25fd6f3_3
   - nlohmann_json-abi==3.12.0=h0f90c79_2
   - pybind11-abi==11=hc364b38_1
   - python_abi==3.14=8_cp314
   - tzdata==2026c=h151e31d_0
   - _openmp_mutex==4.5=20_gnu
   - zstd==1.5.7=hb78ec9c_7
   - ld_impl_linux-64==2.46.1=default_hbd61a6d_102
   - libgcc==16.1.0=ha9f2e26_1
   - bzip2==1.0.8=hda65f42_10
   - c-ares==1.34.8=h280c20c_1
   - keyutils==1.6.3=h7cc23a3_1
   - libev==4.33=h280c20c_3
   - libexpat==2.8.1=hecca717_1
   - libffi==3.7.0=h3435931_0
   - libiconv==1.18=h3b78370_2
   - liblzma==5.8.3=hb03c661_1
   - libmpdec==4.0.0=hb03c661_2
   - libstdcxx==16.1.0=h934c35e_1
   - libuuid==2.42.2=h5347b49_0
   - lzo==2.10=h280c20c_1002
   - ncurses==6.6=hdb14827_1
   - openssl==3.6.3=h35e630c_1
   - reproc==14.2.7.post0=h54a6638_2
   - tk==8.6.13=noxft_hd70dff1_3
   - cpp-expected==1.3.1=h171cf75_1
   - fmt==12.1.0=h76c4fd7_1
   - icu==78.3=py310h44b86e0_2
   - libedit==3.1.20250104=pl5321h373387f_1
   - libnghttp2==1.68.1=h877daf1_0
   - libsolv==0.7.39=h9463b59_0
   - libssh2==1.11.1=h6154650_1
   - lz4-c==1.10.0=hee9eb32_2
   - readline==8.3=h853b02a_0
   - reproc-cpp==14.2.7.post0=h50b1954_2
   - simdjson==4.2.4=hb700be7_0
   - yaml-cpp==0.8.0=h54a6638_1
   - krb5==1.22.2=hbc21106_2
   - libpsl==0.23.1=hf670292_0
   - libsqlite==3.53.4=hf4e2dac_0
   - libxml2-16==2.15.3=hca6bf5a_0
   - spdlog==1.17.0=hb6aa676_2
   - libcurl==8.21.0=heca4667_4
   - libxml2==2.15.3=h49c6c72_0
   - python==3.14.6=h242f9ac_102_cp314
   - libarchive==3.8.9=gpl_hc2c16d8_100
   - tomli-w==1.2.0=pyhd8ed1ab_0
   - libmamba==2.5.0=hd28c85e_0
   - menuinst==2.5.2=py314h9e666f3_1
   - archspec==0.2.5=pyhd8ed1ab_0
   - backports.zstd==1.6.0=py314h680f03e_0
   - boltons==26.1.0=pyhd8ed1ab_0
   - brotli-python==1.2.0=py314hcd2bdb6_3
   - cached_property==1.5.2=pyha770c72_2
   - certifi==2026.7.22=pyhd8ed1ab_0
   - charset-normalizer==3.5.0=pyhd8ed1ab_0
   - colorama==0.4.6=pyhd8ed1ab_1
   - cpython==3.14.6=py314hd8ed1ab_102
   - distro==1.9.0=pyhd8ed1ab_1
   - filelock==3.32.3=pyhd8ed1ab_0
   - frozendict==2.4.7=pyh851646a_2
   - hpack==4.2.0=pyhd8ed1ab_0
   - hyperframe==6.1.0=pyhd8ed1ab_0
   - idna==3.18=pyhcf101f3_0
   - jsonpointer==3.1.1=pyhcf101f3_0
   - libmamba-spdlog==2.5.0=h12fcf84_0
   - mamba==2.5.0=h9835478_0
   - markupsafe==3.0.3=py314h67df5f8_1
   - msgpack-python==1.2.1=py314h97ea11e_1
   - packaging==26.3=pyhc364b38_0
   - pip==26.2.1=pyh145f28c_0
   - platformdirs==4.11.3=pyhcf101f3_0
   - pluggy==1.6.0=pyhf9edf01_1
   - pycosat==0.6.6=py314h5bd0f2a_4
   - pycparser==3.0=pyhcf101f3_0
   - pysocks==1.7.1=pyha55dd90_7
   - python-installer==1.0.1=pyh332efcf_0
   - ruamel.yaml.clib==0.2.15=py314h0f05182_1
   - setuptools==84.0.0=pyh332efcf_0
   - sniffio==1.3.1=pyhd8ed1ab_2
   - tomli==2.4.1=pyhcf101f3_0
   - tqdm==4.70.0=pyh8f84b5b_0
   - truststore==0.10.4=pyhcf101f3_0
   - typing_extensions==4.16.0=pyhcf101f3_0
   - zipp==4.1.0=pyhcf101f3_0
   - cached-property==1.5.2=hd8ed1ab_2
   - cffi==2.1.1=py314h8d76f0c_2
   - conda-package-streaming==0.13.0=pyhd8ed1ab_0
   - exceptiongroup==1.3.1=pyhd8ed1ab_0
   - h11==0.16.0=pyhcf101f3_1
   - h2==4.4.1=pyhcf101f3_0
   - importlib-metadata==9.0.0=pyhcf101f3_0
   - jinja2==3.1.6=pyhcf101f3_1
   - jsonpatch==1.33=pyhd8ed1ab_1
   - libmambapy==2.5.0=py314hcbd71af_0
   - pyproject_hooks==1.2.0=pyhd8ed1ab_1
   - python-gil==3.14.6=h4df99d1_102
   - ruamel.yaml==0.18.17=py314h0f05182_2
   - typing-extensions==4.16.0=h69aa097_0
   - typing-inspection==0.4.3=pyhcf101f3_0
   - _python_abi3_support==1.0=hd8ed1ab_3
   - annotated-types==0.8.0=pyhd8ed1ab_0
   - anyio==4.14.2=pyhcf101f3_0
   - conda-libmamba-solver==26.7.0=pyhcf101f3_0
   - pydantic-core==2.46.4=py314h2e6c369_0
   - python-build==1.5.0=pyhc364b38_0
   - urllib3==2.7.0=pyhd8ed1ab_0
   - zstandard==0.25.0=py314h0f05182_1
   - httpcore==1.0.9=pyh29332c3_0
   - py-rattler==0.25.0=py310h70157a2_2
   - pydantic==2.13.4=pyhcf101f3_0
   - requests==2.34.2=pyhcf101f3_0
   - conda-package-handling==2.5.0=pyhcf101f3_0
   - httpx==0.28.1=pyhd8ed1ab_0
   - unearth==0.18.2=pyhd8ed1ab_0
   - conda-pypi==0.11.0=py314h9e666f3_1
   - conda-index==0.12.1=pyhd8ed1ab_0
   - conda-lockfiles==0.2.1=pyhd8ed1ab_0
   - conda-rattler-solver==0.1.1=pyhcf101f3_0
   - conda==26.5.3=py314h9e666f3_2
   - conda-self==0.2.1=pyhd8ed1ab_0


  Package                         Version  Build                 Channel         Size
───────────────────────────────────────────────────────────────────────────────────────
  Install:
───────────────────────────────────────────────────────────────────────────────────────

  + _openmp_mutex                     4.5  20_gnu                conda-forge
  + _python_abi3_support              1.0  hd8ed1ab_3            conda-forge
  + annotated-types                 0.8.0  pyhd8ed1ab_0          conda-forge
  + anyio                          4.14.2  pyhcf101f3_0          conda-forge
  + archspec                        0.2.5  pyhd8ed1ab_0          conda-forge
  + backports.zstd                  1.6.0  py314h680f03e_0       conda-forge
  + boltons                        26.1.0  pyhd8ed1ab_0          conda-forge
  + brotli-python                   1.2.0  py314hcd2bdb6_3       conda-forge
  + bzip2                           1.0.8  hda65f42_10           conda-forge
  + c-ares                         1.34.8  h280c20c_1            conda-forge
  + ca-certificates             2026.7.22  hbd8a1cb_0            conda-forge
  + cached-property                 1.5.2  hd8ed1ab_2            conda-forge
  + cached_property                 1.5.2  pyha770c72_2          conda-forge
  + certifi                     2026.7.22  pyhd8ed1ab_0          conda-forge
  + cffi                            2.1.1  py314h8d76f0c_2       conda-forge
  + charset-normalizer              3.5.0  pyhd8ed1ab_0          conda-forge
  + colorama                        0.4.6  pyhd8ed1ab_1          conda-forge
  + conda                          26.5.3  py314h9e666f3_2       conda-forge
  + conda-index                    0.12.1  pyhd8ed1ab_0          conda-forge
  + conda-libmamba-solver          26.7.0  pyhcf101f3_0          conda-forge
  + conda-lockfiles                 0.2.1  pyhd8ed1ab_0          conda-forge
  + conda-package-handling          2.5.0  pyhcf101f3_0          conda-forge
  + conda-package-streaming        0.13.0  pyhd8ed1ab_0          conda-forge
  + conda-pypi                     0.11.0  py314h9e666f3_1       conda-forge
  + conda-rattler-solver            0.1.1  pyhcf101f3_0          conda-forge
  + conda-self                      0.2.1  pyhd8ed1ab_0          conda-forge
  + cpp-expected                    1.3.1  h171cf75_1            conda-forge
  + cpython                        3.14.6  py314hd8ed1ab_102     conda-forge
  + distro                          1.9.0  pyhd8ed1ab_1          conda-forge
  + exceptiongroup                  1.3.1  pyhd8ed1ab_0          conda-forge
  + filelock                       3.32.3  pyhd8ed1ab_0          conda-forge
  + fmt                            12.1.0  h76c4fd7_1            conda-forge
  + frozendict                      2.4.7  pyh851646a_2          conda-forge
  + h11                            0.16.0  pyhcf101f3_1          conda-forge
  + h2                              4.4.1  pyhcf101f3_0          conda-forge
  + hpack                           4.2.0  pyhd8ed1ab_0          conda-forge
  + httpcore                        1.0.9  pyh29332c3_0          conda-forge
  + httpx                          0.28.1  pyhd8ed1ab_0          conda-forge
  + hyperframe                      6.1.0  pyhd8ed1ab_0          conda-forge
  + icu                              78.3  py310h44b86e0_2       conda-forge
  + idna                             3.18  pyhcf101f3_0          conda-forge
  + importlib-metadata              9.0.0  pyhcf101f3_0          conda-forge
  + jinja2                          3.1.6  pyhcf101f3_1          conda-forge
  + jsonpatch                        1.33  pyhd8ed1ab_1          conda-forge
  + jsonpointer                     3.1.1  pyhcf101f3_0          conda-forge
  + keyutils                        1.6.3  h7cc23a3_1            conda-forge
  + krb5                           1.22.2  hbc21106_2            conda-forge
  + ld_impl_linux-64               2.46.1  default_hbd61a6d_102  conda-forge
  + libarchive                      3.8.9  gpl_hc2c16d8_100      conda-forge
  + libcurl                        8.21.0  heca4667_4            conda-forge
  + libedit                  3.1.20250104  pl5321h373387f_1      conda-forge
  + libev                            4.33  h280c20c_3            conda-forge
  + libexpat                        2.8.1  hecca717_1            conda-forge
  + libffi                          3.7.0  h3435931_0            conda-forge
  + libgcc                         16.1.0  ha9f2e26_1            conda-forge
  + libgomp                        16.1.0  he0feb66_1            conda-forge
  + libiconv                         1.18  h3b78370_2            conda-forge
  + liblzma                         5.8.3  hb03c661_1            conda-forge
  + libmamba                        2.5.0  hd28c85e_0            conda-forge
  + libmamba-spdlog                 2.5.0  h12fcf84_0            conda-forge
  + libmambapy                      2.5.0  py314hcbd71af_0       conda-forge
  + libmpdec                        4.0.0  hb03c661_2            conda-forge
  + libnghttp2                     1.68.1  h877daf1_0            conda-forge
  + libpsl                         0.23.1  hf670292_0            conda-forge
  + libsolv                        0.7.39  h9463b59_0            conda-forge
  + libsqlite                      3.53.4  hf4e2dac_0            conda-forge
  + libssh2                        1.11.1  h6154650_1            conda-forge
  + libstdcxx                      16.1.0  h934c35e_1            conda-forge
  + libuuid                        2.42.2  h5347b49_0            conda-forge
  + libxml2                        2.15.3  h49c6c72_0            conda-forge
  + libxml2-16                     2.15.3  hca6bf5a_0            conda-forge
  + libzlib                         1.3.2  h25fd6f3_3            conda-forge
  + lz4-c                          1.10.0  hee9eb32_2            conda-forge
  + lzo                              2.10  h280c20c_1002         conda-forge
  + mamba                           2.5.0  h9835478_0            conda-forge
  + markupsafe                      3.0.3  py314h67df5f8_1       conda-forge
  + menuinst                        2.5.2  py314h9e666f3_1       conda-forge
  + msgpack-python                  1.2.1  py314h97ea11e_1       conda-forge
  + ncurses                           6.6  hdb14827_1            conda-forge
  + nlohmann_json-abi              3.12.0  h0f90c79_2            conda-forge
  + openssl                         3.6.3  h35e630c_1            conda-forge
  + packaging                        26.3  pyhc364b38_0          conda-forge
  + pip                            26.2.1  pyh145f28c_0          conda-forge
  + platformdirs                   4.11.3  pyhcf101f3_0          conda-forge
  + pluggy                          1.6.0  pyhf9edf01_1          conda-forge
  + py-rattler                     0.25.0  py310h70157a2_2       conda-forge
  + pybind11-abi                       11  hc364b38_1            conda-forge
  + pycosat                         0.6.6  py314h5bd0f2a_4       conda-forge
  + pycparser                         3.0  pyhcf101f3_0          conda-forge
  + pydantic                       2.13.4  pyhcf101f3_0          conda-forge
  + pydantic-core                  2.46.4  py314h2e6c369_0       conda-forge
  + pyproject_hooks                 1.2.0  pyhd8ed1ab_1          conda-forge
  + pysocks                         1.7.1  pyha55dd90_7          conda-forge
  + python                         3.14.6  h242f9ac_102_cp314    conda-forge
  + python-build                    1.5.0  pyhc364b38_0          conda-forge
  + python-gil                     3.14.6  h4df99d1_102          conda-forge
  + python-installer                1.0.1  pyh332efcf_0          conda-forge
  + python_abi                       3.14  8_cp314               conda-forge
  + readline                          8.3  h853b02a_0            conda-forge
  + reproc                   14.2.7.post0  h54a6638_2            conda-forge
  + reproc-cpp               14.2.7.post0  h50b1954_2            conda-forge
  + requests                       2.34.2  pyhcf101f3_0          conda-forge
  + ruamel.yaml                   0.18.17  py314h0f05182_2       conda-forge
  + ruamel.yaml.clib               0.2.15  py314h0f05182_1       conda-forge
  + setuptools                     84.0.0  pyh332efcf_0          conda-forge
  + simdjson                        4.2.4  hb700be7_0            conda-forge
  + sniffio                         1.3.1  pyhd8ed1ab_2          conda-forge
  + spdlog                         1.17.0  hb6aa676_2            conda-forge
  + tk                             8.6.13  noxft_hd70dff1_3      conda-forge
  + tomli                           2.4.1  pyhcf101f3_0          conda-forge
  + tomli-w                         1.2.0  pyhd8ed1ab_0          conda-forge
  + tqdm                           4.70.0  pyh8f84b5b_0          conda-forge
  + truststore                     0.10.4  pyhcf101f3_0          conda-forge
  + typing-extensions              4.16.0  h69aa097_0            conda-forge
  + typing-inspection               0.4.3  pyhcf101f3_0          conda-forge
  + typing_extensions              4.16.0  pyhcf101f3_0          conda-forge
  + tzdata                          2026c  h151e31d_0            conda-forge
  + unearth                        0.18.2  pyhd8ed1ab_0          conda-forge
  + urllib3                         2.7.0  pyhd8ed1ab_0          conda-forge
  + yaml-cpp                        0.8.0  h54a6638_1            conda-forge
  + zipp                            4.1.0  pyhcf101f3_0          conda-forge
  + zstandard                      0.25.0  py314h0f05182_1       conda-forge

In [3]:
# Install the official PyTorch and requirements inside the isolated env
!/content/miniforge3/bin/conda run -n tddpm pip install --upgrade pip==23.3.1
!/content/miniforge3/bin/conda run -n tddpm pip install torch==1.10.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html
!/content/miniforge3/bin/conda run -n tddpm pip install -r /content/tab-ddpm/requirements.txt

Collecting pip==23.3.1
  Downloading pip-23.3.1-py3-none-any.whl.metadata (3.5 kB)
Downloading pip-23.3.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 21.0 MB/s  0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 25.2
    Uninstalling pip-25.2:
      Successfully uninstalled pip-25.2
Successfully installed pip-23.3.1
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torch==1.10.1+cu111
  Downloading https://download.pytorch.org/whl/cu111/torch-1.10.1%2Bcu111-cp39-cp39-linux_x86_64.whl (2137.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 GB 713.2 kB/s eta 0:00:00
Collecting typing-extensions (from torch==1.10.1+cu111)
  Downloading typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Downloading typing_extensions-4.16.0-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 1.1 MB/s eta 0:00:00
Installing collected packages: typing-extensions, torch
Successfully installed torch-1.10.1+cu111 typing-extensions-4.16.0
Collecting catboost==1.0.3 (from -r /content/tab-ddpm/requirements.txt (line 1))
  Downloading catboost-1.0.3-cp39-none-manylinux1_x86_64.whl.metadata (1.2 kB)
Collecting category-encoders==2.3.0 (from -r /content/tab-ddpm/requirements.txt (line 2))
  Downloading category_encoders-2.3.0-py2.py3-none-any.whl.metadata (6.8 kB)
Collecting dython==0.5.1 (from -r /content/tab-ddpm/requirements.txt (line 3))
  Downloading dython-0.5.1-py3-none-any.whl.metadata (1.8 kB)
Collecting icecream==2.1.2 (from -r /content/tab-ddpm/requirements.txt (line 4))
  Downloading icecream-2.1.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting libzero==0.0.8 (from -r /content/tab-ddpm/requirements.txt (line 5))
  Downloading libzero-0.0.8-py3-none-any.whl.metadata (888 bytes)
Collecting numpy==1.21.4 (from -r /content/tab-ddpm/requirements.txt (line 6))
  Downloading numpy-1.21.4-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (2.1 kB)
Collecting optuna==2.10.1 (from -r /content/tab-ddpm/requirements.txt (line 7))
  Downloading optuna-2.10.1-py3-none-any.whl.metadata (15 kB)
Collecting pandas==1.3.4 (from -r /content/tab-ddpm/requirements.txt (line 8))
  Downloading pandas-1.3.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting pyarrow==6.0.0 (from -r /content/tab-ddpm/requirements.txt (line 9))
  Downloading pyarrow-6.0.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.9 kB)
Collecting rtdl==0.0.9 (from -r /content/tab-ddpm/requirements.txt (line 10))
  Downloading rtdl-0.0.9-py3-none-any.whl.metadata (1.0 kB)
Collecting scikit-learn==1.0.2 (from -r /content/tab-ddpm/requirements.txt (line 11))
  Downloading scikit_learn-1.0.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Collecting scipy==1.7.2 (from -r /content/tab-ddpm/requirements.txt (line 12))
  Downloading scipy-1.7.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.2 kB)
Collecting skorch==0.11.0 (from -r /content/tab-ddpm/requirements.txt (line 13))
  Downloading skorch-0.11.0-py3-none-any.whl.metadata (9.3 kB)
Collecting tomli-w==0.4.0 (from -r /content/tab-ddpm/requirements.txt (line 14))
  Downloading tomli_w-0.4.0-py3-none-any.whl.metadata (5.0 kB)
Collecting tomli==1.2.2 (from -r /content/tab-ddpm/requirements.txt (line 15))
  Downloading tomli-1.2.2-py3-none-any.whl.metadata (9.1 kB)
Collecting tqdm==4.62.3 (from -r /content/tab-ddpm/requirements.txt (line 16))
  Downloading tqdm-4.62.3-py2.py3-none-any.whl.metadata (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.0/57.0 kB 1.3 MB/s eta 0:00:00
Collecting imbalanced-learn==0.7.0 (from -r /content/tab-ddpm/requirements.txt (line 19))
  Downloading imbalanced_learn-0.7.0-py3-none-any.whl.metadata (11 kB)
Collecting rdt==0.6.4 (from -r /content/tab-ddpm/requirements.txt (line 22))
  Downloading rdt-0.6.4-py2.py3-none-any.whl.metadata (37 kB)
Collecting graphviz (from catboost==1.0.3->-r /content/tab-ddpm/requirements.txt (line 1))
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Collecting matplotlib (from catboost==1.0.3->-r /content/tab-ddpm/requirements.txt (line 1))
  Downloading matplotlib-3.9.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting plotly (from catboost==1.0.3->-r /content/tab-ddpm/requirements.txt (line 1))
  Downloading plotly-7.0.0-py3-none-any.whl.metadata (8.7 kB)
Collecting six (from catboost==1.0.3->-r /content/tab-ddpm/requirements.txt (line 1))
  Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting statsmodels>=0.9.0 (from category-encoders==2.3.0->-r /content/tab-ddpm/requirements.txt (line 2))
  Downloading statsmodels-0.14.6-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Collecting patsy>=0.5.1 (from category-encoders==2.3.0->-r /content/tab-ddpm/requirements.txt (line 2))
  Downloading patsy-1.0.3-py2.py3-none-any.whl.metadata (3.7 kB)
Collecting seaborn (from dython==0.5.1->-r /content/tab-ddpm/requirements.txt (line 3))
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting colorama>=0.3.9 (from icecream==2.1.2->-r /content/tab-ddpm/requirements.txt (line 4))
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting pygments>=2.2.0 (from icecream==2.1.2->-r /content/tab-ddpm/requirements.txt (line 4))
  Downloading pygments-2.21.0-py3-none-any.whl.metadata (2.5 kB)
Collecting executing>=0.3.1 (from icecream==2.1.2->-r /content/tab-ddpm/requirements.txt (line 4))
  Downloading executing-2.2.1-py2.py3-none-any.whl.metadata (8.9 kB)
Collecting asttokens>=2.0.1 (from icecream==2.1.2->-r /content/tab-ddpm/requirements.txt (line 4))
  Downloading asttokens-3.0.2-py3-none-any.whl.metadata (5.7 kB)
Collecting pynvml<12,>=11.0 (from libzero==0.0.8->-r /content/tab-ddpm/requirements.txt (line 5))
  Downloading pynvml-11.5.3-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: torch<2,>=1.7 in /content/miniforge3/envs/tddpm/lib/python3.9/site-packages (from libzero==0.0.8->-r /content/tab-ddpm/requirements.txt (line 5)) (1.10.1+cu111)
Collecting alembic (from optuna==2.10.1->-r /content/tab-ddpm/requirements.txt (line 7))
  Downloading alembic-1.16.5-py3-none-any.whl.metadata (7.3 kB)
Collecting cliff (from optuna==2.10.1->-r /content/tab-ddpm/requirements.txt (line 7))
  Downloading cliff-4.9.1-py3-none-any.whl.metadata (2.1 kB)
Collecting cmaes>=0.8.2 (from optuna==2.10.1->-r /content/tab-ddpm/requirements.txt (line 7))
  Downloading cmaes-0.13.1-py3-none-any.whl.metadata (29 kB)
Collecting colorlog (from optuna==2.10.1->-r /content/tab-ddpm/requirements.txt (line 7))
  Downloading colorlog-6.12.0-py3-none-any.whl.metadata (11 kB)
Collecting packaging>=20.0 (from optuna==2.10.1->-r /content/tab-ddpm/requirements.txt (line 7))
  Downloading packaging-26.3-py3-none-any.whl.metadata (3.5 kB)
Collecting sqlalchemy>=1.1.0 (from optuna==2.10.1->-r /content/tab-ddpm/requirements.txt (line 7))
  Downloading sqlalchemy-2.0.52-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.6 kB)
Collecting PyYAML (from optuna==2.10.1->-r /content/tab-ddpm/requirements.txt (line 7))
  Downloading pyyaml-6.0.3-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting python-dateutil>=2.7.3 (from pandas==1.3.4->-r /content/tab-ddpm/requirements.txt (line 8))
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2017.3 (from pandas==1.3.4->-r /content/tab-ddpm/requirements.txt (line 8))
  Downloading pytz-2026.3.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting joblib>=0.11 (from scikit-learn==1.0.2->-r /content/tab-ddpm/requirements.txt (line 11))
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=2.0.0 (from scikit-learn==1.0.2->-r /content/tab-ddpm/requirements.txt (line 11))
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting tabulate>=0.7.7 (from skorch==0.11.0->-r /content/tab-ddpm/requirements.txt (line 13))
  Downloading tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Collecting psutil<6,>=5.7 (from rdt==0.6.4->-r /content/tab-ddpm/requirements.txt (line 22))
  Downloading psutil-5.9.8-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (21 kB)
Collecting PyYAML (from optuna==2.10.1->-r /content/tab-ddpm/requirements.txt (line 7))
  Downloading PyYAML-5.4.1-cp39-cp39-manylinux1_x86_64.whl.metadata (2.1 kB)
Collecting greenlet>=1 (from sqlalchemy>=1.1.0->optuna==2.10.1->-r /content/tab-ddpm/requirements.txt (line 7))
  Downloading greenlet-3.2.5-cp39-cp39-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in /content/miniforge3/envs/tddpm/lib/python3.9/site-packages (from sqlalchemy>=1.1.0->optuna==2.10.1->-r /content/tab-ddpm/requirements.txt (line 7)) (4.16.0)
INFO: pip is looking at multiple versions of statsmodels to determine which version is compatible with other requirements. This could take a while.
Collecting statsmodels>=0.9.0 (from category-encoders==2.3.0->-r /content/tab-ddpm/requirements.txt (line 2))
  Downloading statsmodels-0.14.5-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.5 kB)
  Downloading statsmodels-0.14.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.2 kB)
  Downloading statsmodels-0.14.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.2 kB)
  Downloading statsmodels-0.14.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.2 kB)
  Downloading statsmodels-0.14.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.5 kB)
Collecting Mako (from alembic->optuna==2.10.1->-r /content/tab-ddpm/requirements.txt (line 7))
  Downloading mako-1.3.12-py3-none-any.whl.metadata (2.9 kB)
Collecting autopage>=0.4.0 (from cliff->optuna==2.10.1->-r /content/tab-ddpm/requirements.txt (line 7))
  Downloading autopage-0.6.0-py3-none-any.whl.metadata (8.1 kB)
Collecting cmd2>=1.0.0 (from cliff->optuna==2.10.1->-r /content/tab-ddpm/requirements.txt (line 7))
  Downloading cmd2-2.7.0-py3-none-any.whl.metadata (17 kB)
Collecting PrettyTable>=0.7.2 (from cliff->optuna==2.10.1->-r /content/tab-ddpm/requirements.txt (line 7))
  Downloading prettytable-3.16.0-py3-none-any.whl.metadata (33 kB)
Collecting stevedore>=2.0.1 (from cliff->optuna==2.10.1->-r /content/tab-ddpm/requirements.txt (line 7))
  Downloading stevedore-5.5.0-py3-none-any.whl.metadata (2.2 kB)
Collecting importlib-metadata>=4.4 (from cliff->optuna==2.10.1->-r /content/tab-ddpm/requirements.txt (line 7))
  Downloading importlib_metadata-8.7.1-py3-none-any.whl.metadata (4.7 kB)
Collecting contourpy>=1.0.1 (from matplotlib->catboost==1.0.3->-r /content/tab-ddpm/requirements.txt (line 1))
  Downloading contourpy-1.3.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.4 kB)
Collecting cycler>=0.10 (from matplotlib->catboost==1.0.3->-r /content/tab-ddpm/requirements.txt (line 1))
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib->catboost==1.0.3->-r /content/tab-ddpm/requirements.txt (line 1))
  Downloading fonttools-4.60.2-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (113 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 113.5/113.5 kB 2.8 MB/s eta 0:00:00
Collecting kiwisolver>=1.3.1 (from matplotlib->catboost==1.0.3->-r /content/tab-ddpm/requirements.txt (line 1))
  Downloading kiwisolver-1.4.7-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (6.3 kB)
INFO: pip is looking at multiple versions of matplotlib to determine which version is compatible with other requirements. This could take a while.
Collecting matplotlib (from catboost==1.0.3->-r /content/tab-ddpm/requirements.txt (line 1))
  Downloading matplotlib-3.9.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
  Downloading matplotlib-3.9.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
  Downloading matplotlib-3.9.1.post1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
  Downloading matplotlib-3.9.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
  Downloading matplotlib-3.8.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.8 kB)
Collecting pillow>=8 (from matplotlib->catboost==1.0.3->-r /content/tab-ddpm/requirements.txt (line 1))
  Downloading pillow-11.3.0-cp39-cp39-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.0 kB)
Collecting pyparsing>=2.3.1 (from matplotlib->catboost==1.0.3->-r /content/tab-ddpm/requirements.txt (line 1))
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting importlib-resources>=3.2.0 (from matplotlib->catboost==1.0.3->-r /content/tab-ddpm/requirements.txt (line 1))
  Downloading importlib_resources-6.5.2-py3-none-any.whl.metadata (3.9 kB)
Collecting narwhals>=1.15.1 (from plotly->catboost==1.0.3->-r /content/tab-ddpm/requirements.txt (line 1))
  Downloading narwhals-2.21.0-py3-none-any.whl.metadata (16 kB)
Collecting pyperclip>=1.8 (from cmd2>=1.0.0->cliff->optuna==2.10.1->-r /content/tab-ddpm/requirements.txt (line 7))
  Downloading pyperclip-1.11.0-py3-none-any.whl.metadata (2.4 kB)
Collecting rich-argparse>=1.7.1 (from cmd2>=1.0.0->cliff->optuna==2.10.1->-r /content/tab-ddpm/requirements.txt (line 7))
  Downloading rich_argparse-1.8.0-py3-none-any.whl.metadata (15 kB)
Collecting wcwidth>=0.2.10 (from cmd2>=1.0.0->cliff->optuna==2.10.1->-r /content/tab-ddpm/requirements.txt (line 7))
  Downloading wcwidth-0.8.3-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/43.3 kB 3.6 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of contourpy to determine which version is compatible with other requirements. This could take a while.
Collecting contourpy>=1.0.1 (from matplotlib->catboost==1.0.3->-r /content/tab-ddpm/requirements.txt (line 1))
  Downloading contourpy-1.2.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.8 kB)
Collecting zipp>=3.20 (from importlib-metadata>=4.4->cliff->optuna==2.10.1->-r /content/tab-ddpm/requirements.txt (line 7))
  Downloading zipp-3.23.1-py3-none-any.whl.metadata (3.6 kB)
Collecting MarkupSafe>=0.9.2 (from Mako->alembic->optuna==2.10.1->-r /content/tab-ddpm/requirements.txt (line 7))
  Downloading markupsafe-3.0.3-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.7 kB)
Collecting rich>=11.0.0 (from rich-argparse>=1.7.1->cmd2>=1.0.0->cliff->optuna==2.10.1->-r /content/tab-ddpm/requirements.txt (line 7))
  Downloading rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=11.0.0->rich-argparse>=1.7.1->cmd2>=1.0.0->cliff->optuna==2.10.1->-r /content/tab-ddpm/requirements.txt (line 7))
  Downloading markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=11.0.0->rich-argparse>=1.7.1->cmd2>=1.0.0->cliff->optuna==2.10.1->-r /content/tab-ddpm/requirements.txt (line 7))
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading catboost-1.0.3-cp39-none-manylinux1_x86_64.whl (76.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.3/76.3 MB 4.7 MB/s eta 0:00:00
Downloading category_encoders-2.3.0-py2.py3-none-any.whl (82 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.2/82.2 kB 4.6 MB/s eta 0:00:00
Downloading dython-0.5.1-py3-none-any.whl (14 kB)
Downloading icecream-2.1.2-py2.py3-none-any.whl (8.3 kB)
Downloading libzero-0.0.8-py3-none-any.whl (28 kB)
Downloading numpy-1.21.4-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 16.5 MB/s eta 0:00:00
Downloading optuna-2.10.1-py3-none-any.whl (308 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 308.2/308.2 kB 22.1 MB/s eta 0:00:00
Downloading pandas-1.3.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.5/11.5 MB 14.8 MB/s eta 0:00:00
Downloading pyarrow-6.0.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.6/25.6 MB 13.8 MB/s eta 0:00:00
Downloading rtdl-0.0.9-py3-none-any.whl (24 kB)
Downloading scikit_learn-1.0.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.4/26.4 MB 32.5 MB/s eta 0:00:00
Downloading scipy-1.7.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (39.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.8/39.8 MB 10.7 MB/s eta 0:00:00
Downloading skorch-0.11.0-py3-none-any.whl (155 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.1/155.1 kB 12.5 MB/s eta 0:00:00
Downloading tomli_w-0.4.0-py3-none-any.whl (6.0 kB)
Downloading tomli-1.2.2-py3-none-any.whl (12 kB)
Downloading tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.2/76.2 kB 6.8 MB/s eta 0:00:00
Downloading imbalanced_learn-0.7.0-py3-none-any.whl (167 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.1/167.1 kB 15.3 MB/s eta 0:00:00
Downloading rdt-0.6.4-py2.py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.9/45.9 kB 4.2 MB/s eta 0:00:00
Downloading asttokens-3.0.2-py3-none-any.whl (28 kB)
Downloading cmaes-0.13.1-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.4/73.4 kB 7.6 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading executing-2.2.1-py2.py3-none-any.whl (28 kB)
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 309.1/309.1 kB 23.7 MB/s eta 0:00:00
Downloading packaging-26.3-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.0/130.0 kB 12.9 MB/s eta 0:00:00
Downloading patsy-1.0.3-py2.py3-none-any.whl (233 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.3/233.3 kB 20.3 MB/s eta 0:00:00
Downloading psutil-5.9.8-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (288 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.2/288.2 kB 23.6 MB/s eta 0:00:00
Downloading pygments-2.21.0-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 30.7 MB/s eta 0:00:00
Downloading pynvml-11.5.3-py3-none-any.whl (53 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.1/53.1 kB 4.8 MB/s eta 0:00:00
Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 20.2 MB/s eta 0:00:00
Downloading pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 508.3/508.3 kB 30.5 MB/s eta 0:00:00
Downloading PyYAML-5.4.1-cp39-cp39-manylinux1_x86_64.whl (630 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 630.1/630.1 kB 29.0 MB/s eta 0:00:00
Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
Downloading sqlalchemy-2.0.52-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 35.2 MB/s eta 0:00:00
Downloading statsmodels-0.14.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 16.1 MB/s eta 0:00:00
Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Downloading alembic-1.16.5-py3-none-any.whl (247 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.4/247.4 kB 20.8 MB/s eta 0:00:00
Downloading cliff-4.9.1-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.6/84.6 kB 8.3 MB/s eta 0:00:00

# Setup Libraries

In [4]:
import random
import json

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer

# Load Dataset & Preparation

In [5]:
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ["Pregnancies", "Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI", "DiabetesPedigreeFunction", "Age", "Outcome"]

df = pd.read_csv(url, header=None, names=columns)

TARGET = "Outcome"
FEATURES = df.columns.drop(TARGET)

In [6]:
Zeros = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]

X = df[FEATURES].copy()
y = df[TARGET].astype(int)

for col in Zeros:
    X[col] = X[col].replace(0, np.nan)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

In [7]:
imputer = KNNImputer(n_neighbors=5)

X_train = pd.DataFrame(
    imputer.fit_transform(X_train),
    columns=FEATURES,
    index=X_train.index
)

X_test = pd.DataFrame(
    imputer.transform(X_test),
    columns=FEATURES,
    index=X_test.index
)

In [8]:
X_train_final, X_val, y_train_final, y_val = train_test_split(
    X_train.values.astype("float32"),
    y_train.values.astype("int64"),
    test_size=0.20,
    random_state=42,
    stratify=y_train
)

In [9]:
DATA_DIR = "/content/tab-ddpm/data/pima"
os.makedirs(DATA_DIR, exist_ok=True)

np.save(f"{DATA_DIR}/X_num_train.npy", X_train_final)
np.save(f"{DATA_DIR}/X_num_val.npy", X_val)
np.save(f"{DATA_DIR}/X_num_test.npy", X_test.values.astype("float32"))

np.save(f"{DATA_DIR}/y_train.npy", y_train_final)
np.save(f"{DATA_DIR}/y_val.npy", y_val)
np.save(f"{DATA_DIR}/y_test.npy", y_test.values.astype("int64"))

with open(f"{DATA_DIR}/info.json", "w") as f:
    json.dump({
        "task_type": "binclass",
        "n_classes": 2
    }, f)

# Train Process

### Config

In [10]:
EXP_DIR = "/content/tab-ddpm/exp/pima/ddpm"

os.makedirs(EXP_DIR, exist_ok=True)

config = f"""
seed = 42
parent_dir = "{EXP_DIR}"
real_data_path = "{DATA_DIR}"

model_type = "mlp"
num_numerical_features = 8
device = "cpu"

[model_params]

is_y_cond = true
d_in = 8
num_classes = 2

[model_params.rtdl_params]

d_layers = [256, 256]
dropout = 0.0

[diffusion_params]

num_timesteps = 1000
gaussian_loss_type = "mse"
scheduler = "cosine"

[train.main]

steps = 1000
lr = 0.001
weight_decay = 1e-05
batch_size = 128

[train.T]

seed = 42
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[sample]

num_samples = 1000
batch_size = 1000
seed = 42

[eval.type]

eval_model = "simple"
eval_type = "synthetic"

[eval.T]

seed = 42
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
"""

with open(f"{EXP_DIR}/config.toml", "w") as f:
    f.write(config)

### Tran & Generate 1000 Sample

In [11]:
%cd /content/tab-ddpm

!/content/miniforge3/bin/conda run -n tddpm \
    env PYTHONPATH=/content/tab-ddpm \
    PROJECT_DIR=/content/tab-ddpm \
    python scripts/pipeline.py \
    --config /content/tab-ddpm/exp/pima/ddpm/config.toml \
    --train \
    --sample

/content/tab-ddpm
[0]
8
{'is_y_cond': True, 'd_in': 8, 'num_classes': 2, 'rtdl_params': {'d_layers': [256, 256], 'dropout': 0.0}}
mlp
Step 500/1000 MLoss: 0.0 GLoss: 0.4551 Sum: 0.4551
Step 1000/1000 MLoss: 0.0 GLoss: 0.4417 Sum: 0.4417
mlp
Sample timestep  999
Sample timestep  998
Sample timestep  997
Sample timestep  996
Sample timestep  995
Sample timestep  994
Sample timestep  993
Sample timestep  992
Sample timestep  991
Sample timestep  990
Sample timestep  989
Sample timestep  988
Sample timestep  987
Sample timestep  986
Sample timestep  985
Sample timestep  984
Sample timestep  983
Sample timestep  982
Sample timestep  981
Sample timestep  980
Sample timestep  979
Sample timestep  978
Sample timestep  977
Sample timestep  976
Sample timestep  975
Sample timestep  974
Sample timestep  973
Sample timestep  972
Sample timestep  971
Sample timestep  970
Sample timestep  969
Sample timestep  968
Sample timestep  967
Sample timestep  966
Sample timestep  965
Sample timestep  964
Sample timestep  963
Sample timestep  962
Sample timestep  961
Sample timestep  960
Sample timestep  959
Sample timestep  958
Sample timestep  957
Sample timestep  956
Sample timestep  955
Sample timestep  954
Sample timestep  953
Sample timestep  952
Sample timestep  951
Sample timestep  950
Sample timestep  949
Sample timestep  948
Sample timestep  947
Sample timestep  946
Sample timestep  945
Sample timestep  944
Sample timestep  943
Sample timestep  942
Sample timestep  941
Sample timestep  940
Sample timestep  939
Sample timestep  938
Sample timestep  937
Sample timestep  936
Sample timestep  935
Sample timestep  934
Sample timestep  933
Sample timestep  932
Sample timestep  931
Sample timestep  930
Sample timestep  929
Sample timestep  928
Sample timestep  927
Sample timestep  926
Sample timestep  925
Sample timestep  924
Sample timestep  923
Sample timestep  922
Sample timestep  921
Sample timestep  920
Sample timestep  919
Sample timestep  918
Sample timestep  917
Sample timestep  916
Sample timestep  915
Sample timestep  914
Sample timestep  913
Sample timestep  912
Sample timestep  911
Sample timestep  910
Sample timestep  909
Sample timestep  908
Sample timestep  907
Sample timestep  906
Sample timestep  905
Sample timestep  904
Sample timestep  903
Sample timestep  902
Sample timestep  901
Sample timestep  900
Sample timestep  899
Sample timestep  898
Sample timestep  897
Sample timestep  896
Sample timestep  895
Sample timestep  894
Sample timestep  893
Sample timestep  892
Sample timestep  891
Sample timestep  890
Sample timestep  889
Sample timestep  888
Sample timestep  887
Sample timestep  886
Sample timestep  885
Sample timestep  884
Sample timestep  883
Sample timestep  882
Sample timestep  881
Sample timestep  880
Sample timestep  879
Sample timestep  878
Sample timestep  877
Sample timestep  876
Sample timestep  875
Sample timestep  874
Sample timestep  873
Sample timestep  872
Sample timestep  871
Sample timestep  870
Sample timestep  869
Sample timestep  868
Sample timestep  867
Sample timestep  866
Sample timestep  865
Sample timestep  864
Sample timestep  863
Sample timestep  862
Sample timestep  861
Sample timestep  860
Sample timestep  859
Sample timestep  858
Sample timestep  857
Sample timestep  856
Sample timestep  855
Sample timestep  854
Sample timestep  853
Sample timestep  852
Sample timestep  851
Sample timestep  850
Sample timestep  849
Sample timestep  848
Sample timestep  847
Sample timestep  846
Sample timestep  845
Sample timestep  844
Sample timestep  843
Sample timestep  842
Sample timestep  841
Sample timestep  840
Sample timestep  839
Sample timestep  838
Sample timestep  837
Sample timestep  836
Sample timestep  835
Sample timestep  834
Sample timestep  833
Sample timestep  832
Sample timestep  831
Sample timestep  830
Sample timestep  829
Sample timestep  828
Sample timestep  827
Sample timestep  826
Sample timestep  825
Sample timestep  824
Sample timestep  823
Sample timestep  822
Sample timestep  821
Sample timestep  820
Sample timestep  819
Sample timestep  818
Sample timestep  817
Sample timestep  816
Sample timestep  815
Sample timestep  814
Sample timestep  813
Sample timestep  812
Sample timestep  811
Sample timestep  810
Sample timestep  809
Sample timestep  808
Sample timestep  807
Sample timestep  806
Sample timestep  805
Sample timestep  804
Sample timestep  803
Sample timestep  802
Sample timestep  801
Sample timestep  800
Sample timestep  799
Sample timestep  798
Sample timestep  797
Sample timestep  796
Sample timestep  795
Sample timestep  794
Sample timestep  793
Sample timestep  792
Sample timestep  791
Sample timestep  790
Sample timestep  789
Sample timestep  788
Sample timestep  787
Sample timestep  786
Sample timestep  785
Sample timestep  784
Sample timestep  783
Sample timestep  782
Sample timestep  781
Sample timestep  780
Sample timestep  779
Sample timestep  778
Sample timestep  777
Sample timestep  776
Sample timestep  775
Sample timestep  774
Sample timestep  773
Sample timestep  772
Sample timestep  771
Sample timestep  770
Sample timestep  769
Sample timestep  768
Sample timestep  767
Sample timestep  766
Sample timestep  765
Sample timestep  764
Sample timestep  763
Sample timestep  762
Sample timestep  761
Sample timestep  760
Sample timestep  759
Sample timestep  758
Sample timestep  757
Sample timestep  756
Sample timestep  755
Sample timestep  754
Sample timestep  753
Sample timestep  752
Sample timestep  751
Sample timestep  750
Sample timestep  749
Sample timestep  748
Sample timestep  747
Sample timestep  746
Sample timestep  745
Sample timestep  744
Sample timestep  743
Sample timestep  742
Sample timestep  741
Sample timestep  740
Sample timestep  739
Sample timestep  738
Sample timestep  737
Sample timestep  736
Sample timestep  735
Sample timestep  734
Sample timestep  733
Sample timestep  732
Sample timestep  731
Sample timestep  730
Sample timestep  729
Sample timestep  728
Sample timestep  727
Sample timestep  726
Sample timestep  725
Sample timestep  724
Sample timestep  723
Sample timestep  722
Sample timestep  721
Sample timestep  720
Sample timestep  719
Sample timestep  718
Sample timestep  717
Sample timestep  716
Sample timestep  715
Sample timestep  714
Sample timestep  713
Sample timestep  712
Sample timestep  711
Sample timestep  710
Sample timestep  709
Sample timestep  708
Sample timestep  707
Sample timestep  706
Sample timestep  705
Sample timestep  704
Sample timestep  703
Sample timestep  702
Sample timestep  701
Sample timestep  700
Sample timestep  699
Sample timestep  698
Sample timestep  697
Sample timestep  696
Sample timestep  695
Sample timestep  694
Sample timestep  693
Sample timestep  692
Sample timestep  691
Sample timestep  690
Sample timestep  689
Sample timestep  688
Sample timestep  687
Sample timestep  686
Sample timestep  685
Sample timestep  684
Sample timestep  683
Sample timestep  682
Sample timestep  681
Sample timestep  680
Sample timestep  679
Sample timestep  678
Sample timestep  677
Sample timestep  676
Sample timestep  675
Sample timestep  674
Sample timestep  673
Sample timestep  672
Sample timestep  671
Sample timestep  670
Sample timestep  669
Sample timestep  668
Sample timestep  667
Sample timestep  666
Sample timestep  665
Sample timestep  664
Sample timestep  663
Sample timestep  662
Sample timestep  661
Sample timestep  660
Sample timestep  659
Sample timestep  658
Sample timestep  657
Sample timestep  656
Sample timestep  655
Sample timestep  654
Sample timestep  653
Sample timestep  652
Sample timestep  651
Sample timestep  650
Sample timestep  649
Sample timestep  648
Sample timestep  647
Sample timestep  646
Sample timestep  645
Sample timestep  644
Sample timestep  643
Sample timestep  642
Sample timestep  641
Sample timestep  640
Sample timestep  639
Sample timestep  638
Sample timestep  637
Sample timestep  636
Sample timestep  635
Sample timestep  634
Sample timestep  633
Sample timestep  632
Sample timestep  631
Sample timestep  630
Sample timestep  629
Sample timestep  628
Sample timestep  627
Sample timestep  626
Sample timestep  625
Sample timestep  624
Sample timestep  623
Sample timestep  622
Sample timestep  621
Sample timestep  620
Sample timestep  619
Sample timestep  618
Sample timestep  617
Sample timestep  616
Sample timestep  615
Sample timestep  614
Sample timestep  613
Sample timestep  612
Sample timestep  611
Sample timestep  610
Sample timestep  609
Sample timestep  608
Sample timestep  607
Sample timestep  606
Sample timestep  605
Sample timestep  604
Sample timestep  603
Sample timestep  602
Sample timestep  601
Sample timestep  600
Sample timestep  599
Sample timestep  598
Sample timestep  597
Sample timestep  596
Sample timestep  595
Sample timestep  594
Sample timestep  593
Sample timestep  592
Sample timestep  591
Sample timestep  590
Sample timestep  589
Sample timestep  588
Sample timestep  587
Sample timestep  586
Sample timestep  585
Sample timestep  584
Sample timestep  583
Sample timestep  582
Sample timestep  581
Sample timestep  580
Sample timestep  579
Sample timestep  578
Sample timestep  577
Sample timestep  576
Sample timestep  575
Sample timestep  574
Sample timestep  573
Sample timestep  572
Sample timestep  571
Sample timestep  570
Sample timestep  569
Sample timestep  568
Sample timestep  567
Sample timestep  566
Sample timestep  565
Sample timestep  564
Sample timestep  563
Sample timestep  562
Sample timestep  561
Sample timestep  560
Sample timestep  559
Sample timestep  558
Sample timestep  557
Sample timestep  556
Sample timestep  555
Sample timestep  554
Sample timestep  553
Sample timestep  552
Sample timestep  551
Sample timestep  550
Sample timestep  549
Sample timestep  548
Sample timestep  547
Sample timestep  546
Sample timestep  545
Sample timestep  544
Sample timestep  543
Sample timestep  542
Sample timestep  541
Sample timestep  540
Sample timestep  539
Sample timestep  538
Sample timestep  537
Sample timestep  536
Sample timestep  535
Sample timestep  534
Sample timestep  533
Sample timestep  532
Sample timestep  531
Sample timestep  530
Sample timestep  529
Sample timestep  528
Sample timestep  527
Sample timestep  526
Sample timestep  525
Sample timestep  524
Sample timestep  523
Sample timestep  522
Sample timestep  521
Sample timestep  520
Sample timestep  519
Sample timestep  518
Sample timestep  517
Sample timestep  516
Sample timestep  515
Sample timestep  514
Sample timestep  513
Sample timestep  512
Sample timestep  511
Sample timestep  510
Sample timestep  509
Sample timestep  508
Sample timestep  507
Sample timestep  506
Sample timestep  505
Sample timestep  504
Sample timestep  503
Sample timestep  502
Sample timestep  501
Sample timestep  500
Sample timestep  499
Sample timestep  498
Sample timestep  497
Sample timestep  496
Sample timestep  495
Sample timestep  494
Sample timestep  493
Sample timestep  492
Sample timestep  491
Sample timestep  490
Sample timestep  489
Sample timestep  488
Sample timestep  487
Sample timestep  486
Sample timestep  485
Sample timestep  484
Sample timestep  483
Sample timestep  482
Sample timestep  481
Sample timestep  480
Sample timestep  479
Sample timestep  478
Sample timestep  477
Sample timestep  476
Sample timestep  475
Sample timestep  474
Sample timestep  473
Sample timestep  472
Sample timestep  471
Sample timestep  470
Sample timestep  469
Sample timestep  468
Sample timestep  467
Sample timestep  466
Sample timestep  465
Sample timestep  464
Sample timestep  463
Sample timestep  462
Sample timestep  461
Sample timestep  460
Sample timestep  459
Sample timestep  458
Sample timestep  457
Sample timestep  456
Sample timestep  455
Sample timestep  454
Sample timestep  453
Sample timestep  452
Sample timestep  451
Sample timestep  450
Sample timestep  449
Sample timestep  448
Sample timestep  447
Sample timestep  446
Sample timestep  445
Sample timestep  444
Sample timestep  443
Sample timestep  442
Sample timestep  441
Sample timestep  440
Sample timestep  439
Sample timestep  438
Sample timestep  437
Sample timestep  436
Sample timestep  435
Sample timestep  434
Sample timestep  433
Sample timestep  432
Sample timestep  431
Sample timestep  430
Sample timestep  429
Sample timestep  428
Sample timestep  427
Sample timestep  426
Sample timestep  425
Sample timestep  424
Sample timestep  423
Sample timestep  422
Sample timestep  421
Sample timestep  420
Sample timestep  419
Sample timestep  418
Sample timestep  417
Sample timestep  416
Sample timestep  415
Sample timestep  414
Sample timestep  413
Sample timestep  412
Sample timestep  411
Sample timestep  410
Sample timestep  409
Sample timestep  408
Sample timestep  407
Sample timestep  406
Sample timestep  405
Sample timestep  404
Sample timestep  403
Sample timestep  402
Sample timestep  401
Sample timestep  400
Sample timestep  399
Sample timestep  398
Sample timestep  397
Sample timestep  396
Sample timestep  395
Sample timestep  394
Sample timestep  393
Sample timestep  392
Sample timestep  391
Sample timestep  390
Sample timestep  389
Sample timestep  388
Sample timestep  387
Sample timestep  386
Sample timestep  385
Sample timestep  384
Sample timestep  383
Sample timestep  382
Sample timestep  381
Sample timestep  380
Sample timestep  379
Sample timestep  378
Sample timestep  377
Sample timestep  376
Sample timestep  375
Sample timestep  374
Sample timestep  373
Sample timestep  372
Sample timestep  371
Sample timestep  370
Sample timestep  369
Sample timestep  368
Sample timestep  367
Sample timestep  366
Sample timestep  365
Sample timestep  364
Sample timestep  363
Sample timestep  362
Sample timestep  361
Sample timestep  360
Sample timestep  359
Sample timestep  358
Sample timestep  357
Sample timestep  356
Sample timestep  355
Sample timestep  354
Sample timestep  353
Sample timestep  352
Sample timestep  351
Sample timestep  350
Sample timestep  349
Sample timestep  348
Sample timestep  347
Sample timestep  346
Sample timestep  345
Sample timestep  344
Sample timestep  343
Sample timestep  342
Sample timestep  341
Sample timestep  340
Sample timestep  339
Sample timestep  338
Sample timestep  337
Sample timestep  336
Sample timestep  335
Sample timestep  334
Sample timestep  333
Sample timestep  332
Sample timestep  331
Sample timestep  330
Sample timestep  329
Sample timestep  328
Sample timestep  327
Sample timestep  326
Sample timestep  325
Sample timestep  324
Sample timestep  323
Sample timestep  322
Sample timestep  321
Sample timestep  320
Sample timestep  319
Sample timestep  318
Sample timestep  317
Sample timestep  316
Sample timestep  315
Sample timestep  314
Sample timestep  313
Sample timestep  312
Sample timestep  311
Sample timestep  310
Sample timestep  309
Sample timestep  308
Sample timestep  307
Sample timestep  306
Sample timestep  305
Sample timestep  304
Sample timestep  303
Sample timestep  302
Sample timestep  301
Sample timestep  300
Sample timestep  299
Sample timestep  298
Sample timestep  297
Sample timestep  296
Sample timestep  295
Sample timestep  294
Sample timestep  293
Sample timestep  292
Sample timestep  291
Sample timestep  290
Sample timestep  289
Sample timestep  288
Sample timestep  287
Sample timestep  286
Sample timestep  285
Sample timestep  284
Sample timestep  283
Sample timestep  282
Sample timestep  281
Sample timestep  280
Sample timestep  279
Sample timestep  278
Sample timestep  277
Sample timestep  276
Sample timestep  275
Sample timestep  274
Sample timestep  273
Sample timestep  272
Sample timestep  271
Sample timestep  270
Sample timestep  269
Sample timestep  268
Sample timestep  267
Sample timestep  266
Sample timestep  265
Sample timestep  264
Sample timestep  263
Sample timestep  262
Sample timestep  261
Sample timestep  260
Sample timestep  259
Sample timestep  258
Sample timestep  257
Sample timestep  256
Sample timestep  255
Sample timestep  254
Sample timestep  253
Sample timestep  252
Sample timestep  251
Sample timestep  250
Sample timestep  249
Sample timestep  248
Sample timestep  247
Sample timestep  246
Sample timestep  245
Sample timestep  244
Sample timestep  243
Sample timestep  242
Sample timestep  241
Sample timestep  240
Sample timestep  239
Sample timestep  238
Sample timestep  237
Sample timestep  236
Sample timestep  235
Sample timestep  234
Sample timestep  233
Sample timestep  232
Sample timestep  231
Sample timestep  230
Sample timestep  229
Sample timestep  228
Sample timestep  227
Sample timestep  226
Sample timestep  225
Sample timestep  224
Sample timestep  223
Sample timestep  222
Sample timestep  221
Sample timestep  220
Sample timestep  219
Sample timestep  218
Sample timestep  217
Sample timestep  216
Sample timestep  215
Sample timestep  214
Sample timestep  213
Sample timestep  212
Sample timestep  211
Sample timestep  210
Sample timestep  209
Sample timestep  208
Sample timestep  207
Sample timestep  206
Sample timestep  205
Sample timestep  204
Sample timestep  203
Sample timestep  202
Sample timestep  201
Sample timestep  200
Sample timestep  199
Sample timestep  198
Sample timestep  197
Sample timestep  196
Sample timestep  195
Sample timestep  194
Sample timestep  193
Sample timestep  192
Sample timestep  191
Sample timestep  190
Sample timestep  189
Sample timestep  188
Sample timestep  187
Sample timestep  186
Sample timestep  185
Sample timestep  184
Sample timestep  183
Sample timestep  182
Sample timestep  181
Sample timestep  180
Sample timestep  179
Sample timestep  178
Sample timestep  177
Sample timestep  176
Sample timestep  175
Sample timestep  174
Sample timestep  173
Sample timestep  172
Sample timestep  171
Sample timestep  170
Sample timestep  169
Sample timestep  168
Sample timestep  167
Sample timestep  166
Sample timestep  165
Sample timestep  164
Sample timestep  163
Sample timestep  162
Sample timestep  161
Sample timestep  160
Sample timestep  159
Sample timestep  158
Sample timestep  157
Sample timestep  156
Sample timestep  155
Sample timestep  154
Sample timestep  153
Sample timestep  152
Sample timestep  151
Sample timestep  150
Sample timestep  149
Sample timestep  148
Sample timestep  147
Sample timestep  146
Sample timestep  145
Sample timestep  144
Sample timestep  143
Sample timestep  142
Sample timestep  141
Sample timestep  140
Sample timestep  139
Sample timestep  138
Sample timestep  137
Sample timestep  136
Sample timestep  135
Sample timestep  134
Sample timestep  133
Sample timestep  132
Sample timestep  131
Sample timestep  130
Sample timestep  129
Sample timestep  128
Sample timestep  127
Sample timestep  126
Sample timestep  125
Sample timestep  124
Sample timestep  123
Sample timestep  122
Sample timestep  121
Sample timestep  120
Sample timestep  119
Sample timestep  118
Sample timestep  117
Sample timestep  116
Sample timestep  115
Sample timestep  114
Sample timestep  113
Sample timestep  112
Sample timestep  111
Sample timestep  110
Sample timestep  109
Sample timestep  108
Sample timestep  107
Sample timestep  106
Sample timestep  105
Sample timestep  104
Sample timestep  103
Sample timestep  102
Sample timestep  101
Sample timestep  100
Sample timestep   99
Sample timestep   98
Sample timestep   97
Sample timestep   96
Sample timestep   95
Sample timestep   94
Sample timestep   93
Sample timestep   92
Sample timestep   91
Sample timestep   90
Sample timestep   89
Sample timestep   88
Sample timestep   87
Sample timestep   86
Sample timestep   85
Sample timestep   84
Sample timestep   83
Sample timestep   82
Sample timestep   81
Sample timestep   80
Sample timestep   79
Sample timestep   78
Sample timestep   77
Sample timestep   76
Sample timestep   75
Sample timestep   74
Sample timestep   73
Sample timestep   72
Sample timestep   71
Sample timestep   70
Sample timestep   69
Sample timestep   68
Sample timestep   67
Sample timestep   66
Sample timestep   65
Sample timestep   64
Sample timestep   63
Sample timestep   62
Sample timestep   61
Sample timestep   60

### Check The Output

In [12]:
synthetic_X = np.load(
    "/content/tab-ddpm/exp/pima/ddpm/X_num_train.npy"
)

synthetic_y = np.load(
    "/content/tab-ddpm/exp/pima/ddpm/y_train.npy"
)

synthetic_tabddpm = pd.DataFrame(
    synthetic_X,
    columns=FEATURES
)

synthetic_tabddpm["Outcome"] = synthetic_y

print(synthetic_tabddpm.shape)

synthetic_tabddpm.head()

(1000, 9)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0.0,198.000000,122.000000,60.000000,744.000000,67.099998,2.329000,21.387747,1
1,5.0,152.845786,70.927922,25.485584,125.157344,35.336241,0.796103,51.662311,0
2,3.0,107.184849,71.023189,20.369569,120.685512,27.734885,0.373422,30.935240,0
3,0.0,198.000000,122.000000,60.000000,744.000000,67.099998,2.329000,21.000000,1
4,8.0,123.204103,84.958656,31.855343,143.199167,35.047391,0.534479,37.139310,1

In [13]:
# Post-process synthetic data to fix data types
int_columns = ['Pregnancies', 'Age', 'Outcome']

for col in int_columns:
    if col in synthetic_tabddpm.columns:
        synthetic_tabddpm[col] = synthetic_tabddpm[col].round()

display(synthetic_tabddpm.head())
print(synthetic_tabddpm.dtypes)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0.0,198.000000,122.000000,60.000000,744.000000,67.099998,2.329000,21.0,1
1,5.0,152.845786,70.927922,25.485584,125.157344,35.336241,0.796103,52.0,0
2,3.0,107.184849,71.023189,20.369569,120.685512,27.734885,0.373422,31.0,0
3,0.0,198.000000,122.000000,60.000000,744.000000,67.099998,2.329000,21.0,1
4,8.0,123.204103,84.958656,31.855343,143.199167,35.047391,0.534479,37.0,1

Pregnancies                 float64
Glucose                     float64
BloodPressure               float64
SkinThickness               float64
Insulin                     float64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                         float64
Outcome                       int64
dtype: object

In [ ]:
# Save to CSV
synthetic_tabddpm.to_csv('/content/tabddpm_raw.csv', index=False)
print("✔ Synthetic data saved")

In [15]:
import shutil
from google.colab import files

model_path = '/content/tab-ddpm/exp/pima/ddpm'
zip_name = 'tabddpm_pima_model'

if os.path.exists(model_path):
    shutil.make_archive(zip_name, 'zip', model_path)
    print(f"✔ Done")
else:
    print("❌ Error")

✔ Done

### Evaluate

In [16]:
%cd /content/tab-ddpm

!/content/miniforge3/bin/conda run -n tddpm \
    env PYTHONPATH=/content/tab-ddpm \
    PROJECT_DIR=/content/tab-ddpm \
    python scripts/pipeline.py \
    --config /content/tab-ddpm/exp/pima/ddpm/config.toml \
    --eval

/content/tab-ddpm
----------------------------------------------------------------------------------------------------
loading synthetic data: /content/tab-ddpm/exp/pima/ddpm
Train size: (1000, 8), Val size (108, 8)
{'seed': 42, 'normalization': 'minmax', 'num_nan_policy': None, 'cat_nan_policy': None, 'cat_min_frequency': None, 'cat_encoding': None, 'y_policy': 'default'}
----------------------------------------------------------------------------------------------------
DecisionTreeClassifier
****************************************************************************************************
[val]
{'acc': 0.7407, 'f1': 0.7122, 'roc_auc': 0.7098}
[test]
{'acc': 0.6797, 'f1': 0.6539, 'roc_auc': 0.6568}
Elapsed time: 0:00:00
/content/miniforge3/envs/tddpm/lib/python3.9/site-packages/torch/torch_version.py:3: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import packaging  # type: ignore[attr-defined]